 matrix L=(0.03, 0.85 , 0.8  ,0.20, -0.20 , 0.25, -0.20\0.00 ,0.00,  0.0, -0.08,  0.08, -0.10  ,0.10\ 0.00, 0.00 ,0.0 , 0.15 , 0.15 ,0.12,  0.12\ 0.10,0.85  ,0.80 , 0.22  ,0.22 , 0.25,  0.20)
 mat list L
 matrix B=( 0 , 0.0 , 0.0 ,0.00, 0.00 , 0.0,  0.0\  0 , 1.5 , 1.5, 0.85,0.85  ,0.3  ,0.4)
  mat list B
 matrix prob =(0.02, 0.6,.08, 0.07, 0.07, 0.07, 0.07) 
 set obs 100000
 gen x1=.
 gen x2=.
 gen k=int(runiform(1,7))
 replace x1 = 0 if _n==1
 replace x2 = 2 if _n==1
 set more off
forval i=2(1)100000 { 
mat x=(x1[`i'-1],x2[`i'-1])
mat a=(L[1,k[`i']],L[3,k[`i']]\L[2,k[`i']],L[4,k[`i']])
mat b=a'*x'+ B[1...,k[`i']]
replace x1=b[1,1] if _n==`i'
replace x2=b[2,1] if _n==`i'
di `i'
}
 
scatter x2 x1 ,color(green) jitter(2)  title("Merry Christmas")
gr_edit style.editstyle declared_ysize(8) editcopy // Graph size
gr_edit plotregion1.AddMarker added_markers editor -.1173865320507047 6.508580319160336
gr_edit plotregion1.added_markers_new = 1
gr_edit plotregion1.added_markers_rec = 1
gr_edit plotregion1.added_markers[1].style.editstyle  marker( symbol(circle) linestyle( width(thin) color(red) pattern(solid) align(default)) fillcolor(red) size(huge) angle(stdarrow) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(zero) backangle(stdarrow) backsymangle(zero)) line( width(thin) color(black) pattern(solid) align(default)) area( linestyle( width(thin) color(ltbluishgray) pattern(solid) align(default)) shadestyle( color(ltbluishgray) intensity(inten100) fill(pattern10))) label( textstyle( horizontal(center) vertical(middle) angle(default) size(small) color(black) position() margin(zero) linestyle( width(thin) color(black) pattern(solid) align(default))) position(6) textgap(half_tiny) horizontal(default) vertical(default)) dots( symbol(circle) linestyle( width(thin) color(black) pattern(solid) align(default)) fillcolor(black) size(vtiny) angle(horizontal) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(medium) backangle(horizontal) backsymangle(zero)) connect(direct) connect_missings(yes) editcopy // edits
gr_edit plotregion1.AddMarker added_markers editor .1183017199695988 4.969224760867189
gr_edit plotregion1.added_markers_new = 2
gr_edit plotregion1.added_markers_rec = 2
gr_edit plotregion1.added_markers[2].style.editstyle  marker( symbol(circle) linestyle( width(thin) color(red) pattern(solid) align(default)) fillcolor(red) size(huge) angle(stdarrow) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(zero) backangle(stdarrow) backsymangle(zero)) line( width(thin) color(black) pattern(solid) align(default)) area( linestyle( width(thin) color(ltbluishgray) pattern(solid) align(default)) shadestyle( color(ltbluishgray) intensity(inten100) fill(pattern10))) label( textstyle( horizontal(center) vertical(middle) angle(default) size(small) color(black) position() margin(zero) linestyle( width(thin) color(black) pattern(solid) align(default))) position(6) textgap(half_tiny) horizontal(default) vertical(default)) dots( symbol(circle) linestyle( width(thin) color(black) pattern(solid) align(default)) fillcolor(black) size(vtiny) angle(horizontal) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(medium) backangle(horizontal) backsymangle(zero)) connect(direct) connect_missings(yes) editcopy // edits
gr_edit plotregion1.AddMarker added_markers editor -.2646916895633944 4.317958947743165
gr_edit plotregion1.added_markers_new = 3
gr_edit plotregion1.added_markers_rec = 3
gr_edit plotregion1.added_markers[3].style.editstyle  marker( symbol(circle) linestyle( width(thin) color(red) pattern(solid) align(default)) fillcolor(red) size(huge) angle(stdarrow) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(zero) backangle(stdarrow) backsymangle(zero)) line( width(thin) color(black) pattern(solid) align(default)) area( linestyle( width(thin) color(ltbluishgray) pattern(solid) align(default)) shadestyle( color(ltbluishgray) intensity(inten100) fill(pattern10))) label( textstyle( horizontal(center) vertical(middle) angle(default) size(small) color(black) position() margin(zero) linestyle( width(thin) color(black) pattern(solid) align(default))) position(6) textgap(half_tiny) horizontal(default) vertical(default)) dots( symbol(circle) linestyle( width(thin) color(black) pattern(solid) align(default)) fillcolor(black) size(vtiny) angle(horizontal) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(medium) backangle(horizontal) backsymangle(zero)) connect(direct) connect_missings(yes) editcopy
// edits

gr_edit plotregion1.AddMarker added_markers editor .0829484821665532 3.98245837734594
gr_edit plotregion1.added_markers_new = 4
gr_edit plotregion1.added_markers_rec = 4
gr_edit plotregion1.added_markers[4].style.editstyle  marker( symbol(circle) linestyle( width(thin) color(red) pattern(solid) align(default)) fillcolor(red) size(huge) angle(stdarrow) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(zero) backangle(stdarrow) backsymangle(zero)) line( width(thin) color(black) pattern(solid) align(default)) area( linestyle( width(thin) color(ltbluishgray) pattern(solid) align(default)) shadestyle( color(ltbluishgray) intensity(inten100) fill(pattern10))) label( textstyle( horizontal(center) vertical(middle) angle(default) size(small) color(black) position() margin(zero) linestyle( width(thin) color(black) pattern(solid) align(default))) position(6) textgap(half_tiny) horizontal(default) vertical(default)) dots( symbol(circle) linestyle( width(thin) color(black) pattern(solid) align(default)) fillcolor(black) size(vtiny) angle(horizontal) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(medium) backangle(horizontal) backsymangle(zero)) connect(direct) connect_missings(yes) editcopy
// edits

gr_edit plotregion1.AddMarker added_markers editor -.4002124344750687 2.936486010813418
gr_edit plotregion1.added_markers_new = 5
gr_edit plotregion1.added_markers_rec = 5
gr_edit plotregion1.added_markers[5].style.editstyle  marker( symbol(circle) linestyle( width(thin) color(red) pattern(solid) align(default)) fillcolor(red) size(huge) angle(stdarrow) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(zero) backangle(stdarrow) backsymangle(zero)) line( width(thin) color(black) pattern(solid) align(default)) area( linestyle( width(thin) color(ltbluishgray) pattern(solid) align(default)) shadestyle( color(ltbluishgray) intensity(inten100) fill(pattern10))) label( textstyle( horizontal(center) vertical(middle) angle(default) size(small) color(black) position() margin(zero) linestyle( width(thin) color(black) pattern(solid) align(default))) position(6) textgap(half_tiny) horizontal(default) vertical(default)) dots( symbol(circle) linestyle( width(thin) color(black) pattern(solid) align(default)) fillcolor(black) size(vtiny) angle(horizontal) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(medium) backangle(horizontal) backsymangle(zero)) connect(direct) connect_missings(yes) editcopy
// edits

gr_edit plotregion1.AddMarker added_markers editor .0122420065604623 2.423367491382368
gr_edit plotregion1.added_markers_new = 6
gr_edit plotregion1.added_markers_rec = 6
gr_edit plotregion1.added_markers[6].style.editstyle  marker( symbol(circle) linestyle( width(thin) color(red) pattern(solid) align(default)) fillcolor(red) size(huge) angle(stdarrow) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(zero) backangle(stdarrow) backsymangle(zero)) line( width(thin) color(black) pattern(solid) align(default)) area( linestyle( width(thin) color(ltbluishgray) pattern(solid) align(default)) shadestyle( color(ltbluishgray) intensity(inten100) fill(pattern10))) label( textstyle( horizontal(center) vertical(middle) angle(default) size(small) color(black) position() margin(zero) linestyle( width(thin) color(black) pattern(solid) align(default))) position(6) textgap(half_tiny) horizontal(default) vertical(default)) dots( symbol(circle) linestyle( width(thin) color(black) pattern(solid) align(default)) fillcolor(black) size(vtiny) angle(horizontal) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(medium) backangle(horizontal) backsymangle(zero)) connect(direct) connect_missings(yes) editcopy
// edits

gr_edit plotregion1.AddMarker added_markers editor .1831159892751819 1.515542418542821
gr_edit plotregion1.added_markers_new = 7
gr_edit plotregion1.added_markers_rec = 7
gr_edit plotregion1.added_markers[7].style.editstyle  marker( symbol(circle) linestyle( width(thin) color(red) pattern(solid) align(default)) fillcolor(red) size(huge) angle(stdarrow) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(zero) backangle(stdarrow) backsymangle(zero)) line( width(thin) color(black) pattern(solid) align(default)) area( linestyle( width(thin) color(ltbluishgray) pattern(solid) align(default)) shadestyle( color(ltbluishgray) intensity(inten100) fill(pattern10))) label( textstyle( horizontal(center) vertical(middle) angle(default) size(small) color(black) position() margin(zero) linestyle( width(thin) color(black) pattern(solid) align(default))) position(6) textgap(half_tiny) horizontal(default) vertical(default)) dots( symbol(circle) linestyle( width(thin) color(black) pattern(solid) align(default)) fillcolor(black) size(vtiny) angle(horizontal) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(medium) backangle(horizontal) backsymangle(zero)) connect(direct) connect_missings(yes) editcopy
// edits

// addedmarker_proto edits

gr_edit plotregion1.AddMarker added_markers editor .0004575939594469 5.778373195354612
gr_edit plotregion1.added_markers_new = 8
gr_edit plotregion1.added_markers_rec = 8
gr_edit plotregion1.added_markers[8].style.editstyle  marker( symbol(circle) linestyle( width(thin) color(red) pattern(solid) align(default)) fillcolor(red) size(medlarge) angle(stdarrow) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(zero) backangle(stdarrow) backsymangle(zero)) line( width(thin) color(black) pattern(solid) align(default)) area( linestyle( width(thin) color(ltbluishgray) pattern(solid) align(default)) shadestyle( color(ltbluishgray) intensity(inten100) fill(pattern10))) label( textstyle( horizontal(center) vertical(middle) angle(default) size(small) color(black) position() margin(zero) linestyle( width(thin) color(black) pattern(solid) align(default))) position(6) textgap(half_tiny) horizontal(default) vertical(default)) dots( symbol(circle) linestyle( width(thin) color(black) pattern(solid) align(default)) fillcolor(black) size(vtiny) angle(horizontal) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(medium) backangle(horizontal) backsymangle(zero)) connect(direct) connect_missings(yes) editcopy
// edits

gr_edit plotregion1.AddMarker added_markers editor -.2352306580608564 5.107372054560163
gr_edit plotregion1.added_markers_new = 9
gr_edit plotregion1.added_markers_rec = 9
gr_edit plotregion1.added_markers[9].style.editstyle  marker( symbol(circle) linestyle( width(thin) color(red) pattern(solid) align(default)) fillcolor(red) size(medlarge) angle(stdarrow) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(zero) backangle(stdarrow) backsymangle(zero)) line( width(thin) color(black) pattern(solid) align(default)) area( linestyle( width(thin) color(ltbluishgray) pattern(solid) align(default)) shadestyle( color(ltbluishgray) intensity(inten100) fill(pattern10))) label( textstyle( horizontal(center) vertical(middle) angle(default) size(small) color(black) position() margin(zero) linestyle( width(thin) color(black) pattern(solid) align(default))) position(6) textgap(half_tiny) horizontal(default) vertical(default)) dots( symbol(circle) linestyle( width(thin) color(black) pattern(solid) align(default)) fillcolor(black) size(vtiny) angle(horizontal) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(medium) backangle(horizontal) backsymangle(zero)) connect(direct) connect_missings(yes) editcopy
// edits

gr_edit plotregion1.AddMarker added_markers editor .0593796569645226 6.844080889557564
gr_edit plotregion1.added_markers_new = 10
gr_edit plotregion1.added_markers_rec = 10
gr_edit plotregion1.added_markers[10].style.editstyle  marker( symbol(circle) linestyle( width(thin) color(red) pattern(solid) align(default)) fillcolor(red) size(medlarge) angle(stdarrow) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(zero) backangle(stdarrow) backsymangle(zero)) line( width(thin) color(black) pattern(solid) align(default)) area( linestyle( width(thin) color(ltbluishgray) pattern(solid) align(default)) shadestyle( color(ltbluishgray) intensity(inten100) fill(pattern10))) label( textstyle( horizontal(center) vertical(middle) angle(default) size(small) color(black) position() margin(zero) linestyle( width(thin) color(black) pattern(solid) align(default))) position(6) textgap(half_tiny) horizontal(default) vertical(default)) dots( symbol(circle) linestyle( width(thin) color(black) pattern(solid) align(default)) fillcolor(black) size(vtiny) angle(horizontal) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(medium) backangle(horizontal) backsymangle(zero)) connect(direct) connect_missings(yes) editcopy
// edits

gr_edit plotregion1.AddMarker added_markers editor -.0997099131491823 2.916750683142993
gr_edit plotregion1.added_markers_new = 11
gr_edit plotregion1.added_markers_rec = 11
gr_edit plotregion1.added_markers[11].style.editstyle  marker( symbol(circle) linestyle( width(thin) color(red) pattern(solid) align(default)) fillcolor(red) size(medlarge) angle(stdarrow) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(zero) backangle(stdarrow) backsymangle(zero)) line( width(thin) color(black) pattern(solid) align(default)) area( linestyle( width(thin) color(ltbluishgray) pattern(solid) align(default)) shadestyle( color(ltbluishgray) intensity(inten100) fill(pattern10))) label( textstyle( horizontal(center) vertical(middle) angle(default) size(small) color(black) position() margin(zero) linestyle( width(thin) color(black) pattern(solid) align(default))) position(6) textgap(half_tiny) horizontal(default) vertical(default)) dots( symbol(circle) linestyle( width(thin) color(black) pattern(solid) align(default)) fillcolor(black) size(vtiny) angle(horizontal) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(medium) backangle(horizontal) backsymangle(zero)) connect(direct) connect_missings(yes) editcopy
// edits

gr_edit plotregion1.AddMarker added_markers editor -.1114943257501971 1.535277746213245
gr_edit plotregion1.added_markers_new = 12
gr_edit plotregion1.added_markers_rec = 12
gr_edit plotregion1.added_markers[12].style.editstyle  marker( symbol(circle) linestyle( width(thin) color(red) pattern(solid) align(default)) fillcolor(red) size(medlarge) angle(stdarrow) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(zero) backangle(stdarrow) backsymangle(zero)) line( width(thin) color(black) pattern(solid) align(default)) area( linestyle( width(thin) color(ltbluishgray) pattern(solid) align(default)) shadestyle( color(ltbluishgray) intensity(inten100) fill(pattern10))) label( textstyle( horizontal(center) vertical(middle) angle(default) size(small) color(black) position() margin(zero) linestyle( width(thin) color(black) pattern(solid) align(default))) position(6) textgap(half_tiny) horizontal(default) vertical(default)) dots( symbol(circle) linestyle( width(thin) color(black) pattern(solid) align(default)) fillcolor(black) size(vtiny) angle(horizontal) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(medium) backangle(horizontal) backsymangle(zero)) connect(direct) connect_missings(yes) editcopy
// edits

gr_edit plotregion1.AddMarker added_markers editor -.4119968470760838 1.357659797179421
gr_edit plotregion1.added_markers_new = 13
gr_edit plotregion1.added_markers_rec = 13
gr_edit plotregion1.added_markers[13].style.editstyle  marker( symbol(circle) linestyle( width(thin) color(red) pattern(solid) align(default)) fillcolor(red) size(medlarge) angle(stdarrow) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(zero) backangle(stdarrow) backsymangle(zero)) line( width(thin) color(black) pattern(solid) align(default)) area( linestyle( width(thin) color(ltbluishgray) pattern(solid) align(default)) shadestyle( color(ltbluishgray) intensity(inten100) fill(pattern10))) label( textstyle( horizontal(center) vertical(middle) angle(default) size(small) color(black) position() margin(zero) linestyle( width(thin) color(black) pattern(solid) align(default))) position(6) textgap(half_tiny) horizontal(default) vertical(default)) dots( symbol(circle) linestyle( width(thin) color(black) pattern(solid) align(default)) fillcolor(black) size(vtiny) angle(horizontal) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(medium) backangle(horizontal) backsymangle(zero)) connect(direct) connect_missings(yes) editcopy
// edits

// addedmarker_proto edits

gr_edit plotregion1.AddMarker added_markers editor -.0525722627451214 5.127107382230587
gr_edit plotregion1.added_markers_new = 14
gr_edit plotregion1.added_markers_rec = 14
gr_edit plotregion1.added_markers[14].style.editstyle  marker( symbol(circle) linestyle( width(thin) color(red) pattern(solid) align(default)) fillcolor(red) size(small) angle(stdarrow) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(zero) backangle(stdarrow) backsymangle(zero)) line( width(thin) color(black) pattern(solid) align(default)) area( linestyle( width(thin) color(ltbluishgray) pattern(solid) align(default)) shadestyle( color(ltbluishgray) intensity(inten100) fill(pattern10))) label( textstyle( horizontal(center) vertical(middle) angle(default) size(small) color(black) position() margin(zero) linestyle( width(thin) color(black) pattern(solid) align(default))) position(6) textgap(half_tiny) horizontal(default) vertical(default)) dots( symbol(circle) linestyle( width(thin) color(black) pattern(solid) align(default)) fillcolor(black) size(vtiny) angle(horizontal) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(medium) backangle(horizontal) backsymangle(zero)) connect(direct) connect_missings(yes) editcopy
// edits

gr_edit plotregion1.AddMarker added_markers editor -.2587994832628867 1.91024897195132
gr_edit plotregion1.added_markers_new = 15
gr_edit plotregion1.added_markers_rec = 15
gr_edit plotregion1.added_markers[15].style.editstyle  marker( symbol(circle) linestyle( width(thin) color(red) pattern(solid) align(default)) fillcolor(red) size(small) angle(stdarrow) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(zero) backangle(stdarrow) backsymangle(zero)) line( width(thin) color(black) pattern(solid) align(default)) area( linestyle( width(thin) color(ltbluishgray) pattern(solid) align(default)) shadestyle( color(ltbluishgray) intensity(inten100) fill(pattern10))) label( textstyle( horizontal(center) vertical(middle) angle(default) size(small) color(black) position() margin(zero) linestyle( width(thin) color(black) pattern(solid) align(default))) position(6) textgap(half_tiny) horizontal(default) vertical(default)) dots( symbol(circle) linestyle( width(thin) color(black) pattern(solid) align(default)) fillcolor(black) size(vtiny) angle(horizontal) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(medium) backangle(horizontal) backsymangle(zero)) connect(direct) connect_missings(yes) editcopy
// edits

gr_edit plotregion1.AddMarker added_markers editor .5425405736061444 2.383896836041519
gr_edit plotregion1.added_markers_new = 16
gr_edit plotregion1.added_markers_rec = 16
gr_edit plotregion1.added_markers[16].style.editstyle  marker( symbol(circle) linestyle( width(thin) color(red) pattern(solid) align(default)) fillcolor(red) size(small) angle(stdarrow) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(zero) backangle(stdarrow) backsymangle(zero)) line( width(thin) color(black) pattern(solid) align(default)) area( linestyle( width(thin) color(ltbluishgray) pattern(solid) align(default)) shadestyle( color(ltbluishgray) intensity(inten100) fill(pattern10))) label( textstyle( horizontal(center) vertical(middle) angle(default) size(small) color(black) position() margin(zero) linestyle( width(thin) color(black) pattern(solid) align(default))) position(6) textgap(half_tiny) horizontal(default) vertical(default)) dots( symbol(circle) linestyle( width(thin) color(black) pattern(solid) align(default)) fillcolor(black) size(vtiny) angle(horizontal) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(medium) backangle(horizontal) backsymangle(zero)) connect(direct) connect_missings(yes) editcopy
// edits

// addedmarker_proto edits

gr_edit plotregion1.AddMarker added_markers editor -.12917094465172 5.896785161377162
gr_edit plotregion1.added_markers_new = 17
gr_edit plotregion1.added_markers_rec = 17
gr_edit plotregion1.added_markers[17].style.editstyle  marker( symbol(circle) linestyle( width(thin) color(gold) pattern(solid) align(default)) fillcolor(gold) size(small) angle(stdarrow) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(zero) backangle(stdarrow) backsymangle(zero)) line( width(thin) color(black) pattern(solid) align(default)) area( linestyle( width(thin) color(ltbluishgray) pattern(solid) align(default)) shadestyle( color(ltbluishgray) intensity(inten100) fill(pattern10))) label( textstyle( horizontal(center) vertical(middle) angle(default) size(small) color(black) position() margin(zero) linestyle( width(thin) color(black) pattern(solid) align(default))) position(6) textgap(half_tiny) horizontal(default) vertical(default)) dots( symbol(circle) linestyle( width(thin) color(black) pattern(solid) align(default)) fillcolor(black) size(vtiny) angle(horizontal) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(medium) backangle(horizontal) backsymangle(zero)) connect(direct) connect_missings(yes) editcopy
// edits

gr_edit plotregion1.AddMarker added_markers editor .0063498002599545 4.949489433196764
gr_edit plotregion1.added_markers_new = 18
gr_edit plotregion1.added_markers_rec = 18
gr_edit plotregion1.added_markers[18].style.editstyle  marker( symbol(circle) linestyle( width(thin) color(gold) pattern(solid) align(default)) fillcolor(gold) size(small) angle(stdarrow) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(zero) backangle(stdarrow) backsymangle(zero)) line( width(thin) color(black) pattern(solid) align(default)) area( linestyle( width(thin) color(ltbluishgray) pattern(solid) align(default)) shadestyle( color(ltbluishgray) intensity(inten100) fill(pattern10))) label( textstyle( horizontal(center) vertical(middle) angle(default) size(small) color(black) position() margin(zero) linestyle( width(thin) color(black) pattern(solid) align(default))) position(6) textgap(half_tiny) horizontal(default) vertical(default)) dots( symbol(circle) linestyle( width(thin) color(black) pattern(solid) align(default)) fillcolor(black) size(vtiny) angle(horizontal) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(medium) backangle(horizontal) backsymangle(zero)) connect(direct) connect_missings(yes) editcopy
// edits

gr_edit plotregion1.AddMarker added_markers editor -.0879255005481669 3.883781738993815
gr_edit plotregion1.added_markers_new = 19
gr_edit plotregion1.added_markers_rec = 19
gr_edit plotregion1.added_markers[19].style.editstyle  marker( symbol(circle) linestyle( width(thin) color(gold) pattern(solid) align(default)) fillcolor(gold) size(small) angle(stdarrow) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(zero) backangle(stdarrow) backsymangle(zero)) line( width(thin) color(black) pattern(solid) align(default)) area( linestyle( width(thin) color(ltbluishgray) pattern(solid) align(default)) shadestyle( color(ltbluishgray) intensity(inten100) fill(pattern10))) label( textstyle( horizontal(center) vertical(middle) angle(default) size(small) color(black) position() margin(zero) linestyle( width(thin) color(black) pattern(solid) align(default))) position(6) textgap(half_tiny) horizontal(default) vertical(default)) dots( symbol(circle) linestyle( width(thin) color(black) pattern(solid) align(default)) fillcolor(black) size(vtiny) angle(horizontal) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(medium) backangle(horizontal) backsymangle(zero)) connect(direct) connect_missings(yes) editcopy
// edits

gr_edit plotregion1.AddMarker added_markers editor -.1763085950557807 3.015427321495117
gr_edit plotregion1.added_markers_new = 20
gr_edit plotregion1.added_markers_rec = 20
gr_edit plotregion1.added_markers[20].style.editstyle  marker( symbol(circle) linestyle( width(thin) color(gold) pattern(solid) align(default)) fillcolor(gold) size(small) angle(stdarrow) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(zero) backangle(stdarrow) backsymangle(zero)) line( width(thin) color(black) pattern(solid) align(default)) area( linestyle( width(thin) color(ltbluishgray) pattern(solid) align(default)) shadestyle( color(ltbluishgray) intensity(inten100) fill(pattern10))) label( textstyle( horizontal(center) vertical(middle) angle(default) size(small) color(black) position() margin(zero) linestyle( width(thin) color(black) pattern(solid) align(default))) position(6) textgap(half_tiny) horizontal(default) vertical(default)) dots( symbol(circle) linestyle( width(thin) color(black) pattern(solid) align(default)) fillcolor(black) size(vtiny) angle(horizontal) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(medium) backangle(horizontal) backsymangle(zero)) connect(direct) connect_missings(yes) editcopy
// edits

gr_edit plotregion1.AddMarker added_markers editor -.3943202281745611 2.06813159331472
gr_edit plotregion1.added_markers_new = 21
gr_edit plotregion1.added_markers_rec = 21
gr_edit plotregion1.added_markers[21].style.editstyle  marker( symbol(circle) linestyle( width(thin) color(gold) pattern(solid) align(default)) fillcolor(gold) size(small) angle(stdarrow) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(zero) backangle(stdarrow) backsymangle(zero)) line( width(thin) color(black) pattern(solid) align(default)) area( linestyle( width(thin) color(ltbluishgray) pattern(solid) align(default)) shadestyle( color(ltbluishgray) intensity(inten100) fill(pattern10))) label( textstyle( horizontal(center) vertical(middle) angle(default) size(small) color(black) position() margin(zero) linestyle( width(thin) color(black) pattern(solid) align(default))) position(6) textgap(half_tiny) horizontal(default) vertical(default)) dots( symbol(circle) linestyle( width(thin) color(black) pattern(solid) align(default)) fillcolor(black) size(vtiny) angle(horizontal) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(medium) backangle(horizontal) backsymangle(zero)) connect(direct) connect_missings(yes) editcopy
// edits

gr_edit plotregion1.AddMarker added_markers editor .3068523215858412 1.436601107861121
gr_edit plotregion1.added_markers_new = 22
gr_edit plotregion1.added_markers_rec = 22
gr_edit plotregion1.added_markers[22].style.editstyle  marker( symbol(circle) linestyle( width(thin) color(gold) pattern(solid) align(default)) fillcolor(gold) size(small) angle(stdarrow) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(zero) backangle(stdarrow) backsymangle(zero)) line( width(thin) color(black) pattern(solid) align(default)) area( linestyle( width(thin) color(ltbluishgray) pattern(solid) align(default)) shadestyle( color(ltbluishgray) intensity(inten100) fill(pattern10))) label( textstyle( horizontal(center) vertical(middle) angle(default) size(small) color(black) position() margin(zero) linestyle( width(thin) color(black) pattern(solid) align(default))) position(6) textgap(half_tiny) horizontal(default) vertical(default)) dots( symbol(circle) linestyle( width(thin) color(black) pattern(solid) align(default)) fillcolor(black) size(vtiny) angle(horizontal) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(medium) backangle(horizontal) backsymangle(zero)) connect(direct) connect_missings(yes) editcopy
// edits

// addedmarker_proto edits

gr_edit plotregion1.AddMarker added_markers editor -.1114943257501971 5.640225901661637
gr_edit plotregion1.added_markers_new = 23
gr_edit plotregion1.added_markers_rec = 23
gr_edit plotregion1.added_markers[23].style.editstyle  marker( symbol(circle) linestyle( width(thin) color(gold) pattern(solid) align(default)) fillcolor(gold) size(medlarge) angle(stdarrow) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(zero) backangle(stdarrow) backsymangle(zero)) line( width(thin) color(black) pattern(solid) align(default)) area( linestyle( width(thin) color(ltbluishgray) pattern(solid) align(default)) shadestyle( color(ltbluishgray) intensity(inten100) fill(pattern10))) label( textstyle( horizontal(center) vertical(middle) angle(default) size(small) color(black) position() margin(zero) linestyle( width(thin) color(black) pattern(solid) align(default))) position(6) textgap(half_tiny) horizontal(default) vertical(default)) dots( symbol(circle) linestyle( width(thin) color(black) pattern(solid) align(default)) fillcolor(black) size(vtiny) angle(horizontal) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(medium) backangle(horizontal) backsymangle(zero)) connect(direct) connect_missings(yes) editcopy
// edits

gr_edit plotregion1.AddMarker added_markers editor .0299186254619848 5.127107382230587
gr_edit plotregion1.added_markers_new = 24
gr_edit plotregion1.added_markers_rec = 24
gr_edit plotregion1.added_markers[24].style.editstyle  marker( symbol(circle) linestyle( width(thin) color(gold) pattern(solid) align(default)) fillcolor(gold) size(medlarge) angle(stdarrow) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(zero) backangle(stdarrow) backsymangle(zero)) line( width(thin) color(black) pattern(solid) align(default)) area( linestyle( width(thin) color(ltbluishgray) pattern(solid) align(default)) shadestyle( color(ltbluishgray) intensity(inten100) fill(pattern10))) label( textstyle( horizontal(center) vertical(middle) angle(default) size(small) color(black) position() margin(zero) linestyle( width(thin) color(black) pattern(solid) align(default))) position(6) textgap(half_tiny) horizontal(default) vertical(default)) dots( symbol(circle) linestyle( width(thin) color(black) pattern(solid) align(default)) fillcolor(black) size(vtiny) angle(horizontal) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(medium) backangle(horizontal) backsymangle(zero)) connect(direct) connect_missings(yes) editcopy
// edits

gr_edit plotregion1.AddMarker added_markers editor -.30004492736644 3.745634445300841
gr_edit plotregion1.added_markers_new = 25
gr_edit plotregion1.added_markers_rec = 25
gr_edit plotregion1.added_markers[25].style.editstyle  marker( symbol(circle) linestyle( width(thin) color(gold) pattern(solid) align(default)) fillcolor(gold) size(medlarge) angle(stdarrow) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(zero) backangle(stdarrow) backsymangle(zero)) line( width(thin) color(black) pattern(solid) align(default)) area( linestyle( width(thin) color(ltbluishgray) pattern(solid) align(default)) shadestyle( color(ltbluishgray) intensity(inten100) fill(pattern10))) label( textstyle( horizontal(center) vertical(middle) angle(default) size(small) color(black) position() margin(zero) linestyle( width(thin) color(black) pattern(solid) align(default))) position(6) textgap(half_tiny) horizontal(default) vertical(default)) dots( symbol(circle) linestyle( width(thin) color(black) pattern(solid) align(default)) fillcolor(black) size(vtiny) angle(horizontal) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(medium) backangle(horizontal) backsymangle(zero)) connect(direct) connect_missings(yes) editcopy
// edits

gr_edit plotregion1.AddMarker added_markers editor .2007926081767046 2.798338717120442
gr_edit plotregion1.added_markers_new = 26
gr_edit plotregion1.added_markers_rec = 26
gr_edit plotregion1.added_markers[26].style.editstyle  marker( symbol(circle) linestyle( width(thin) color(gold) pattern(solid) align(default)) fillcolor(gold) size(medlarge) angle(stdarrow) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(zero) backangle(stdarrow) backsymangle(zero)) line( width(thin) color(black) pattern(solid) align(default)) area( linestyle( width(thin) color(ltbluishgray) pattern(solid) align(default)) shadestyle( color(ltbluishgray) intensity(inten100) fill(pattern10))) label( textstyle( horizontal(center) vertical(middle) angle(default) size(small) color(black) position() margin(zero) linestyle( width(thin) color(black) pattern(solid) align(default))) position(6) textgap(half_tiny) horizontal(default) vertical(default)) dots( symbol(circle) linestyle( width(thin) color(black) pattern(solid) align(default)) fillcolor(black) size(vtiny) angle(horizontal) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(medium) backangle(horizontal) backsymangle(zero)) connect(direct) connect_missings(yes) editcopy
// edits

gr_edit plotregion1.AddMarker added_markers editor -.2411228643613642 1.476071763201971
gr_edit plotregion1.added_markers_new = 27
gr_edit plotregion1.added_markers_rec = 27
gr_edit plotregion1.added_markers[27].style.editstyle  marker( symbol(circle) linestyle( width(thin) color(gold) pattern(solid) align(default)) fillcolor(gold) size(medlarge) angle(stdarrow) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(zero) backangle(stdarrow) backsymangle(zero)) line( width(thin) color(black) pattern(solid) align(default)) area( linestyle( width(thin) color(ltbluishgray) pattern(solid) align(default)) shadestyle( color(ltbluishgray) intensity(inten100) fill(pattern10))) label( textstyle( horizontal(center) vertical(middle) angle(default) size(small) color(black) position() margin(zero) linestyle( width(thin) color(black) pattern(solid) align(default))) position(6) textgap(half_tiny) horizontal(default) vertical(default)) dots( symbol(circle) linestyle( width(thin) color(black) pattern(solid) align(default)) fillcolor(black) size(vtiny) angle(horizontal) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(medium) backangle(horizontal) backsymangle(zero)) connect(direct) connect_missings(yes) editcopy
// edits

// addedmarker_proto edits

gr_edit plotregion1.AddMarker added_markers editor .1359783388711211 5.679696557002487
gr_edit plotregion1.added_markers_new = 28
gr_edit plotregion1.added_markers_rec = 28
gr_edit plotregion1.added_markers[28].style.editstyle  marker( symbol(circle) linestyle( width(thin) color(gold) pattern(solid) align(default)) fillcolor(gold) size(huge) angle(stdarrow) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(zero) backangle(stdarrow) backsymangle(zero)) line( width(thin) color(black) pattern(solid) align(default)) area( linestyle( width(thin) color(ltbluishgray) pattern(solid) align(default)) shadestyle( color(ltbluishgray) intensity(inten100) fill(pattern10))) label( textstyle( horizontal(center) vertical(middle) angle(default) size(small) color(black) position() margin(zero) linestyle( width(thin) color(black) pattern(solid) align(default))) position(6) textgap(half_tiny) horizontal(default) vertical(default)) dots( symbol(circle) linestyle( width(thin) color(black) pattern(solid) align(default)) fillcolor(black) size(vtiny) angle(horizontal) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(medium) backangle(horizontal) backsymangle(zero)) connect(direct) connect_missings(yes) editcopy
// edits

gr_edit plotregion1.AddMarker added_markers editor .0063498002599545 7.219052115295636
gr_edit plotregion1.added_markers_new = 29
gr_edit plotregion1.added_markers_rec = 29
gr_edit plotregion1.added_markers[29].style.editstyle  marker( symbol(circle) linestyle( width(thin) color(gold) pattern(solid) align(default)) fillcolor(gold) size(huge) angle(stdarrow) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(zero) backangle(stdarrow) backsymangle(zero)) line( width(thin) color(black) pattern(solid) align(default)) area( linestyle( width(thin) color(ltbluishgray) pattern(solid) align(default)) shadestyle( color(ltbluishgray) intensity(inten100) fill(pattern10))) label( textstyle( horizontal(center) vertical(middle) angle(default) size(small) color(black) position() margin(zero) linestyle( width(thin) color(black) pattern(solid) align(default))) position(6) textgap(half_tiny) horizontal(default) vertical(default)) dots( symbol(circle) linestyle( width(thin) color(black) pattern(solid) align(default)) fillcolor(black) size(vtiny) angle(horizontal) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(medium) backangle(horizontal) backsymangle(zero)) connect(direct) connect_missings(yes) editcopy
// edits

gr_edit plotregion1.AddMarker added_markers editor -.1763085950557807 3.646957806948716
gr_edit plotregion1.added_markers_new = 30
gr_edit plotregion1.added_markers_rec = 30
gr_edit plotregion1.added_markers[30].style.editstyle  marker( symbol(circle) linestyle( width(thin) color(gold) pattern(solid) align(default)) fillcolor(gold) size(huge) angle(stdarrow) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(zero) backangle(stdarrow) backsymangle(zero)) line( width(thin) color(black) pattern(solid) align(default)) area( linestyle( width(thin) color(ltbluishgray) pattern(solid) align(default)) shadestyle( color(ltbluishgray) intensity(inten100) fill(pattern10))) label( textstyle( horizontal(center) vertical(middle) angle(default) size(small) color(black) position() margin(zero) linestyle( width(thin) color(black) pattern(solid) align(default))) position(6) textgap(half_tiny) horizontal(default) vertical(default)) dots( symbol(circle) linestyle( width(thin) color(black) pattern(solid) align(default)) fillcolor(black) size(vtiny) angle(horizontal) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(medium) backangle(horizontal) backsymangle(zero)) connect(direct) connect_missings(yes) editcopy
// edits

gr_edit plotregion1.AddMarker added_markers editor -.1704163887552731 1.772101678258345
gr_edit plotregion1.added_markers_new = 31
gr_edit plotregion1.added_markers_rec = 31
gr_edit plotregion1.added_markers[31].style.editstyle  marker( symbol(circle) linestyle( width(thin) color(gold) pattern(solid) align(default)) fillcolor(gold) size(huge) angle(stdarrow) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(zero) backangle(stdarrow) backsymangle(zero)) line( width(thin) color(black) pattern(solid) align(default)) area( linestyle( width(thin) color(ltbluishgray) pattern(solid) align(default)) shadestyle( color(ltbluishgray) intensity(inten100) fill(pattern10))) label( textstyle( horizontal(center) vertical(middle) angle(default) size(small) color(black) position() margin(zero) linestyle( width(thin) color(black) pattern(solid) align(default))) position(6) textgap(half_tiny) horizontal(default) vertical(default)) dots( symbol(circle) linestyle( width(thin) color(black) pattern(solid) align(default)) fillcolor(black) size(vtiny) angle(horizontal) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(medium) backangle(horizontal) backsymangle(zero)) connect(direct) connect_missings(yes) editcopy
// edits

gr_edit plotregion1.AddMarker added_markers editor .4011276223939626 1.91024897195132
gr_edit plotregion1.added_markers_new = 32
gr_edit plotregion1.added_markers_rec = 32
gr_edit plotregion1.added_markers[32].style.editstyle  marker( symbol(circle) linestyle( width(thin) color(gold) pattern(solid) align(default)) fillcolor(gold) size(huge) angle(stdarrow) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(zero) backangle(stdarrow) backsymangle(zero)) line( width(thin) color(black) pattern(solid) align(default)) area( linestyle( width(thin) color(ltbluishgray) pattern(solid) align(default)) shadestyle( color(ltbluishgray) intensity(inten100) fill(pattern10))) label( textstyle( horizontal(center) vertical(middle) angle(default) size(small) color(black) position() margin(zero) linestyle( width(thin) color(black) pattern(solid) align(default))) position(6) textgap(half_tiny) horizontal(default) vertical(default)) dots( symbol(circle) linestyle( width(thin) color(black) pattern(solid) align(default)) fillcolor(black) size(vtiny) angle(horizontal) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(medium) backangle(horizontal) backsymangle(zero)) connect(direct) connect_missings(yes) editcopy
// edits

// addedmarker_proto edits

gr_edit plotregion1.AddMarker added_markers editor -.1468475635532427 5.324460658934837
gr_edit plotregion1.added_markers_new = 33
gr_edit plotregion1.added_markers_rec = 33
gr_edit plotregion1.added_markers[33].style.editstyle  marker( symbol(circle) linestyle( width(thin) color(yellow) pattern(solid) align(default)) fillcolor(yellow) size(huge) angle(stdarrow) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(zero) backangle(stdarrow) backsymangle(zero)) line( width(thin) color(black) pattern(solid) align(default)) area( linestyle( width(thin) color(ltbluishgray) pattern(solid) align(default)) shadestyle( color(ltbluishgray) intensity(inten100) fill(pattern10))) label( textstyle( horizontal(center) vertical(middle) angle(default) size(small) color(black) position() margin(zero) linestyle( width(thin) color(black) pattern(solid) align(default))) position(6) textgap(half_tiny) horizontal(default) vertical(default)) dots( symbol(circle) linestyle( width(thin) color(black) pattern(solid) align(default)) fillcolor(black) size(vtiny) angle(horizontal) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(medium) backangle(horizontal) backsymangle(zero)) connect(direct) connect_missings(yes) editcopy
// edits

// addedmarker_proto edits

gr_edit plotregion1.AddMarker added_markers editor -.0643566753461365 4.554782879788265
gr_edit plotregion1.added_markers_new = 34
gr_edit plotregion1.added_markers_rec = 34
gr_edit plotregion1.added_markers[34].style.editstyle  marker( symbol(circle) linestyle( width(thin) color(white) pattern(solid) align(default)) fillcolor(white) size(huge) angle(stdarrow) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(zero) backangle(stdarrow) backsymangle(zero)) line( width(thin) color(black) pattern(solid) align(default)) area( linestyle( width(thin) color(ltbluishgray) pattern(solid) align(default)) shadestyle( color(ltbluishgray) intensity(inten100) fill(pattern10))) label( textstyle( horizontal(center) vertical(middle) angle(default) size(small) color(black) position() margin(zero) linestyle( width(thin) color(black) pattern(solid) align(default))) position(6) textgap(half_tiny) horizontal(default) vertical(default)) dots( symbol(circle) linestyle( width(thin) color(black) pattern(solid) align(default)) fillcolor(black) size(vtiny) angle(horizontal) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(medium) backangle(horizontal) backsymangle(zero)) connect(direct) connect_missings(yes) editcopy
// edits

gr_edit plotregion1.AddMarker added_markers editor -.4296734659776067 4.041664360357216
gr_edit plotregion1.added_markers_new = 35
gr_edit plotregion1.added_markers_rec = 35
gr_edit plotregion1.added_markers[35].style.editstyle  marker( symbol(circle) linestyle( width(thin) color(white) pattern(solid) align(default)) fillcolor(white) size(huge) angle(stdarrow) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(zero) backangle(stdarrow) backsymangle(zero)) line( width(thin) color(black) pattern(solid) align(default)) area( linestyle( width(thin) color(ltbluishgray) pattern(solid) align(default)) shadestyle( color(ltbluishgray) intensity(inten100) fill(pattern10))) label( textstyle( horizontal(center) vertical(middle) angle(default) size(small) color(black) position() margin(zero) linestyle( width(thin) color(black) pattern(solid) align(default))) position(6) textgap(half_tiny) horizontal(default) vertical(default)) dots( symbol(circle) linestyle( width(thin) color(black) pattern(solid) align(default)) fillcolor(black) size(vtiny) angle(horizontal) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(medium) backangle(horizontal) backsymangle(zero)) connect(direct) connect_missings(yes) editcopy
// edits

gr_edit plotregion1.AddMarker added_markers editor -.4178890533765914 2.383896836041519
gr_edit plotregion1.added_markers_new = 36
gr_edit plotregion1.added_markers_rec = 36
gr_edit plotregion1.added_markers[36].style.editstyle  marker( symbol(circle) linestyle( width(thin) color(white) pattern(solid) align(default)) fillcolor(white) size(huge) angle(stdarrow) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(zero) backangle(stdarrow) backsymangle(zero)) line( width(thin) color(black) pattern(solid) align(default)) area( linestyle( width(thin) color(ltbluishgray) pattern(solid) align(default)) shadestyle( color(ltbluishgray) intensity(inten100) fill(pattern10))) label( textstyle( horizontal(center) vertical(middle) angle(default) size(small) color(black) position() margin(zero) linestyle( width(thin) color(black) pattern(solid) align(default))) position(6) textgap(half_tiny) horizontal(default) vertical(default)) dots( symbol(circle) linestyle( width(thin) color(black) pattern(solid) align(default)) fillcolor(black) size(vtiny) angle(horizontal) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(medium) backangle(horizontal) backsymangle(zero)) connect(direct) connect_missings(yes) editcopy
// edits

gr_edit plotregion1.AddMarker added_markers editor -.2293384517603487 2.324690853030243
gr_edit plotregion1.added_markers_new = 37
gr_edit plotregion1.added_markers_rec = 37
gr_edit plotregion1.added_markers[37].style.editstyle  marker( symbol(circle) linestyle( width(thin) color(white) pattern(solid) align(default)) fillcolor(white) size(huge) angle(stdarrow) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(zero) backangle(stdarrow) backsymangle(zero)) line( width(thin) color(black) pattern(solid) align(default)) area( linestyle( width(thin) color(ltbluishgray) pattern(solid) align(default)) shadestyle( color(ltbluishgray) intensity(inten100) fill(pattern10))) label( textstyle( horizontal(center) vertical(middle) angle(default) size(small) color(black) position() margin(zero) linestyle( width(thin) color(black) pattern(solid) align(default))) position(6) textgap(half_tiny) horizontal(default) vertical(default)) dots( symbol(circle) linestyle( width(thin) color(black) pattern(solid) align(default)) fillcolor(black) size(vtiny) angle(horizontal) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(medium) backangle(horizontal) backsymangle(zero)) connect(direct) connect_missings(yes) editcopy
// edits

gr_edit plotregion1.AddMarker added_markers editor .0947328947675685 1.022159226782197
gr_edit plotregion1.added_markers_new = 38
gr_edit plotregion1.added_markers_rec = 38
gr_edit plotregion1.added_markers[38].style.editstyle  marker( symbol(circle) linestyle( width(thin) color(white) pattern(solid) align(default)) fillcolor(white) size(huge) angle(stdarrow) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(zero) backangle(stdarrow) backsymangle(zero)) line( width(thin) color(black) pattern(solid) align(default)) area( linestyle( width(thin) color(ltbluishgray) pattern(solid) align(default)) shadestyle( color(ltbluishgray) intensity(inten100) fill(pattern10))) label( textstyle( horizontal(center) vertical(middle) angle(default) size(small) color(black) position() margin(zero) linestyle( width(thin) color(black) pattern(solid) align(default))) position(6) textgap(half_tiny) horizontal(default) vertical(default)) dots( symbol(circle) linestyle( width(thin) color(black) pattern(solid) align(default)) fillcolor(black) size(vtiny) angle(horizontal) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(medium) backangle(horizontal) backsymangle(zero)) connect(direct) connect_missings(yes) editcopy
// edits

// addedmarker_proto edits

gr_edit plotregion1.AddMarker added_markers editor .1477627514721365 3.706163789959991
gr_edit plotregion1.added_markers_new = 39
gr_edit plotregion1.added_markers_rec = 39
gr_edit plotregion1.added_markers[39].style.editstyle  marker( symbol(circle) linestyle( width(thin) color(white) pattern(solid) align(default)) fillcolor(white) size(medlarge) angle(stdarrow) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(zero) backangle(stdarrow) backsymangle(zero)) line( width(thin) color(black) pattern(solid) align(default)) area( linestyle( width(thin) color(ltbluishgray) pattern(solid) align(default)) shadestyle( color(ltbluishgray) intensity(inten100) fill(pattern10))) label( textstyle( horizontal(center) vertical(middle) angle(default) size(small) color(black) position() margin(zero) linestyle( width(thin) color(black) pattern(solid) align(default))) position(6) textgap(half_tiny) horizontal(default) vertical(default)) dots( symbol(circle) linestyle( width(thin) color(black) pattern(solid) align(default)) fillcolor(black) size(vtiny) angle(horizontal) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(medium) backangle(horizontal) backsymangle(zero)) connect(direct) connect_missings(yes) editcopy
// edits

gr_edit plotregion1.AddMarker added_markers editor .1536549577726443 2.482573474393644
gr_edit plotregion1.added_markers_new = 40
gr_edit plotregion1.added_markers_rec = 40
gr_edit plotregion1.added_markers[40].style.editstyle  marker( symbol(circle) linestyle( width(thin) color(white) pattern(solid) align(default)) fillcolor(white) size(medlarge) angle(stdarrow) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(zero) backangle(stdarrow) backsymangle(zero)) line( width(thin) color(black) pattern(solid) align(default)) area( linestyle( width(thin) color(ltbluishgray) pattern(solid) align(default)) shadestyle( color(ltbluishgray) intensity(inten100) fill(pattern10))) label( textstyle( horizontal(center) vertical(middle) angle(default) size(small) color(black) position() margin(zero) linestyle( width(thin) color(black) pattern(solid) align(default))) position(6) textgap(half_tiny) horizontal(default) vertical(default)) dots( symbol(circle) linestyle( width(thin) color(black) pattern(solid) align(default)) fillcolor(black) size(vtiny) angle(horizontal) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(medium) backangle(horizontal) backsymangle(zero)) connect(direct) connect_missings(yes) editcopy
// edits

gr_edit plotregion1.AddMarker added_markers editor -.3295059588689778 1.041894554452622
gr_edit plotregion1.added_markers_new = 41
gr_edit plotregion1.added_markers_rec = 41
gr_edit plotregion1.added_markers[41].style.editstyle  marker( symbol(circle) linestyle( width(thin) color(white) pattern(solid) align(default)) fillcolor(white) size(medlarge) angle(stdarrow) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(zero) backangle(stdarrow) backsymangle(zero)) line( width(thin) color(black) pattern(solid) align(default)) area( linestyle( width(thin) color(ltbluishgray) pattern(solid) align(default)) shadestyle( color(ltbluishgray) intensity(inten100) fill(pattern10))) label( textstyle( horizontal(center) vertical(middle) angle(default) size(small) color(black) position() margin(zero) linestyle( width(thin) color(black) pattern(solid) align(default))) position(6) textgap(half_tiny) horizontal(default) vertical(default)) dots( symbol(circle) linestyle( width(thin) color(black) pattern(solid) align(default)) fillcolor(black) size(vtiny) angle(horizontal) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(medium) backangle(horizontal) backsymangle(zero)) connect(direct) connect_missings(yes) editcopy
// edits

gr_edit plotregion1.AddMarker added_markers editor -.353074784071008 1.732631022917495
gr_edit plotregion1.added_markers_new = 42
gr_edit plotregion1.added_markers_rec = 42
gr_edit plotregion1.added_markers[42].style.editstyle  marker( symbol(circle) linestyle( width(thin) color(white) pattern(solid) align(default)) fillcolor(white) size(medlarge) angle(stdarrow) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(zero) backangle(stdarrow) backsymangle(zero)) line( width(thin) color(black) pattern(solid) align(default)) area( linestyle( width(thin) color(ltbluishgray) pattern(solid) align(default)) shadestyle( color(ltbluishgray) intensity(inten100) fill(pattern10))) label( textstyle( horizontal(center) vertical(middle) angle(default) size(small) color(black) position() margin(zero) linestyle( width(thin) color(black) pattern(solid) align(default))) position(6) textgap(half_tiny) horizontal(default) vertical(default)) dots( symbol(circle) linestyle( width(thin) color(black) pattern(solid) align(default)) fillcolor(black) size(vtiny) angle(horizontal) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(medium) backangle(horizontal) backsymangle(zero)) connect(direct) connect_missings(yes) editcopy
// edits

// addedmarker_proto edits

// addedmarker_proto edits

gr_edit plotregion1.AddMarker added_markers editor -.3943202281745611 4.021929032686791
gr_edit plotregion1.added_markers_new = 43
gr_edit plotregion1.added_markers_rec = 43
gr_edit plotregion1.added_markers[43].style.editstyle  marker( symbol(circle) linestyle( width(thin) color(blue) pattern(solid) align(default)) fillcolor(blue) size(huge) angle(stdarrow) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(zero) backangle(stdarrow) backsymangle(zero)) line( width(thin) color(black) pattern(solid) align(default)) area( linestyle( width(thin) color(ltbluishgray) pattern(solid) align(default)) shadestyle( color(ltbluishgray) intensity(inten100) fill(pattern10))) label( textstyle( horizontal(center) vertical(middle) angle(default) size(small) color(black) position() margin(zero) linestyle( width(thin) color(black) pattern(solid) align(default))) position(6) textgap(half_tiny) horizontal(default) vertical(default)) dots( symbol(circle) linestyle( width(thin) color(black) pattern(solid) align(default)) fillcolor(black) size(vtiny) angle(horizontal) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(medium) backangle(horizontal) backsymangle(zero)) connect(direct) connect_missings(yes) editcopy
// edits

gr_edit plotregion1.AddMarker added_markers editor .0063498002599545 3.528545840926167
gr_edit plotregion1.added_markers_new = 44
gr_edit plotregion1.added_markers_rec = 44
gr_edit plotregion1.added_markers[44].style.editstyle  marker( symbol(circle) linestyle( width(thin) color(blue) pattern(solid) align(default)) fillcolor(blue) size(huge) angle(stdarrow) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(zero) backangle(stdarrow) backsymangle(zero)) line( width(thin) color(black) pattern(solid) align(default)) area( linestyle( width(thin) color(ltbluishgray) pattern(solid) align(default)) shadestyle( color(ltbluishgray) intensity(inten100) fill(pattern10))) label( textstyle( horizontal(center) vertical(middle) angle(default) size(small) color(black) position() margin(zero) linestyle( width(thin) color(black) pattern(solid) align(default))) position(6) textgap(half_tiny) horizontal(default) vertical(default)) dots( symbol(circle) linestyle( width(thin) color(black) pattern(solid) align(default)) fillcolor(black) size(vtiny) angle(horizontal) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(medium) backangle(horizontal) backsymangle(zero)) connect(direct) connect_missings(yes) editcopy
// edits

gr_edit plotregion1.AddMarker added_markers editor .0475952443635073 6.25202105944481
gr_edit plotregion1.added_markers_new = 45
gr_edit plotregion1.added_markers_rec = 45
gr_edit plotregion1.added_markers[45].style.editstyle  marker( symbol(circle) linestyle( width(thin) color(blue) pattern(solid) align(default)) fillcolor(blue) size(huge) angle(stdarrow) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(zero) backangle(stdarrow) backsymangle(zero)) line( width(thin) color(black) pattern(solid) align(default)) area( linestyle( width(thin) color(ltbluishgray) pattern(solid) align(default)) shadestyle( color(ltbluishgray) intensity(inten100) fill(pattern10))) label( textstyle( horizontal(center) vertical(middle) angle(default) size(small) color(black) position() margin(zero) linestyle( width(thin) color(black) pattern(solid) align(default))) position(6) textgap(half_tiny) horizontal(default) vertical(default)) dots( symbol(circle) linestyle( width(thin) color(black) pattern(solid) align(default)) fillcolor(black) size(vtiny) angle(horizontal) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(medium) backangle(horizontal) backsymangle(zero)) connect(direct) connect_missings(yes) editcopy
// edits

gr_edit plotregion1.AddMarker added_markers editor .3480977656893944 3.094368632176817
gr_edit plotregion1.added_markers_new = 46
gr_edit plotregion1.added_markers_rec = 46
gr_edit plotregion1.added_markers[46].style.editstyle  marker( symbol(circle) linestyle( width(thin) color(blue) pattern(solid) align(default)) fillcolor(blue) size(huge) angle(stdarrow) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(zero) backangle(stdarrow) backsymangle(zero)) line( width(thin) color(black) pattern(solid) align(default)) area( linestyle( width(thin) color(ltbluishgray) pattern(solid) align(default)) shadestyle( color(ltbluishgray) intensity(inten100) fill(pattern10))) label( textstyle( horizontal(center) vertical(middle) angle(default) size(small) color(black) position() margin(zero) linestyle( width(thin) color(black) pattern(solid) align(default))) position(6) textgap(half_tiny) horizontal(default) vertical(default)) dots( symbol(circle) linestyle( width(thin) color(black) pattern(solid) align(default)) fillcolor(black) size(vtiny) angle(horizontal) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(medium) backangle(horizontal) backsymangle(zero)) connect(direct) connect_missings(yes) editcopy
// edits

// addedmarker_proto edits

gr_edit plotregion1.AddMarker added_markers editor -.1468475635532427 4.850812794844639
gr_edit plotregion1.added_markers_new = 47
gr_edit plotregion1.added_markers_rec = 47
gr_edit plotregion1.added_markers[47].style.editstyle  marker( symbol(circle) linestyle( width(thin) color(blue) pattern(solid) align(default)) fillcolor(blue) size(medlarge) angle(stdarrow) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(zero) backangle(stdarrow) backsymangle(zero)) line( width(thin) color(black) pattern(solid) align(default)) area( linestyle( width(thin) color(ltbluishgray) pattern(solid) align(default)) shadestyle( color(ltbluishgray) intensity(inten100) fill(pattern10))) label( textstyle( horizontal(center) vertical(middle) angle(default) size(small) color(black) position() margin(zero) linestyle( width(thin) color(black) pattern(solid) align(default))) position(6) textgap(half_tiny) horizontal(default) vertical(default)) dots( symbol(circle) linestyle( width(thin) color(black) pattern(solid) align(default)) fillcolor(black) size(vtiny) angle(horizontal) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(medium) backangle(horizontal) backsymangle(zero)) connect(direct) connect_missings(yes) editcopy
// edits

gr_edit plotregion1.AddMarker added_markers editor -.1114943257501971 2.600985440416193
gr_edit plotregion1.added_markers_new = 48
gr_edit plotregion1.added_markers_rec = 48
gr_edit plotregion1.added_markers[48].style.editstyle  marker( symbol(circle) linestyle( width(thin) color(blue) pattern(solid) align(default)) fillcolor(blue) size(medlarge) angle(stdarrow) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(zero) backangle(stdarrow) backsymangle(zero)) line( width(thin) color(black) pattern(solid) align(default)) area( linestyle( width(thin) color(ltbluishgray) pattern(solid) align(default)) shadestyle( color(ltbluishgray) intensity(inten100) fill(pattern10))) label( textstyle( horizontal(center) vertical(middle) angle(default) size(small) color(black) position() margin(zero) linestyle( width(thin) color(black) pattern(solid) align(default))) position(6) textgap(half_tiny) horizontal(default) vertical(default)) dots( symbol(circle) linestyle( width(thin) color(black) pattern(solid) align(default)) fillcolor(black) size(vtiny) angle(horizontal) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(medium) backangle(horizontal) backsymangle(zero)) connect(direct) connect_missings(yes) editcopy
// edits

gr_edit plotregion1.AddMarker added_markers editor .2773912900833035 2.699662078768318
gr_edit plotregion1.added_markers_new = 49
gr_edit plotregion1.added_markers_rec = 49
gr_edit plotregion1.added_markers[49].style.editstyle  marker( symbol(circle) linestyle( width(thin) color(blue) pattern(solid) align(default)) fillcolor(blue) size(medlarge) angle(stdarrow) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(zero) backangle(stdarrow) backsymangle(zero)) line( width(thin) color(black) pattern(solid) align(default)) area( linestyle( width(thin) color(ltbluishgray) pattern(solid) align(default)) shadestyle( color(ltbluishgray) intensity(inten100) fill(pattern10))) label( textstyle( horizontal(center) vertical(middle) angle(default) size(small) color(black) position() margin(zero) linestyle( width(thin) color(black) pattern(solid) align(default))) position(6) textgap(half_tiny) horizontal(default) vertical(default)) dots( symbol(circle) linestyle( width(thin) color(black) pattern(solid) align(default)) fillcolor(black) size(vtiny) angle(horizontal) symangle(zero) backsymbol(none) backline( width(thin) color(black) pattern(solid) align(default)) backcolor(black) backsize(medium) backangle(horizontal) backsymangle(zero)) connect(direct) connect_missings(yes) editcopy
// edits


// <end>


